V1.1.7
dimsonson/go-yandex-diploma-tpl pull request #6
Opened 2022-11-29 18:38 UTC by dimsonson

2022-12-02 16:06 UTC, lostsequence commented on cmd/gophermart/main.go
> +	}
обычно в горутине запускают listen and serve и потом слушают канал, когда можно не использовать idleConnsClosed
кстати, в го добавили signal.NotifyContext для такого паттерна, можно заюзать его

2022-12-02 16:49 UTC, lostsequence commented on cmd/gophermart/workerpool/worker.go
> +			wr.timeoutW = time.NewTicker(time.Duration(timeout) * 1000 * time.Millisecond)
не очень понимаю зачем каждый раз увеличивать таймаут, у нас ведь тогда совсем медленно станут обрабатываться заказы
и на текущий цикл это никак не повлияет ведь, у тебя сразу же пойдет выполнение следующего запроса и он опять 429 ошибку получит
наверное тут можно просто подождать заданное количество времени указанного в заголовке

2022-12-02 16:53 UTC, lostsequence commented on cmd/gophermart/workerpool/worker.go
> +func (wr *Worker) Job(task models.Task) {
сюда бы тоже контекст, чтобы на отмену бесконечный цикл прервать
и на wr.quit чтобы тоже вышел

2022-12-02 19:43 UTC, lostsequence commented on internal/handlers/tests/ordermock_test.go
> +			rout.Post("/api/user/orders", h.Load)
для теста хендлера роутер не обязательно создавать, можно просто функцию хендлера вызывать

2022-12-02 19:47 UTC, lostsequence commented on internal/services/tests/ordermock_test.go
> +
давай назовем просто order, ordermock путает немного

2022-12-02 19:50 UTC, lostsequence commented on internal/services/order.go
> +	linkUpd := fmt.Sprintf("%s/api/orders/%s", svc.CalcSys, orderNum)
давай ссылку прямо в pool генерить ? и передадим просто orderNum

2022-12-02 19:52 UTC, lostsequence commented on internal/services/order.go
> +	AppendTask(models.Task)
из интерфейса только append task используется, давай только этот метод оставим

2022-12-02 20:01 UTC, lostsequence requested changes
Поправь, пожалуйста, комментарии

2022-12-04 13:33 UTC, dimsonson commented on internal/services/order.go
> +	linkUpd := fmt.Sprintf("%s/api/orders/%s", svc.CalcSys, orderNum)
готово

. +

2022-12-04 13:33 UTC, dimsonson commented on internal/services/tests/ordermock_test.go
> +
готово

. +

2022-12-04 13:34 UTC, dimsonson commented on internal/services/order.go
> +	AppendTask(models.Task)
готово

. +

2022-12-04 13:53 UTC, dimsonson commented on internal/handlers/tests/ordermock_test.go
> +			rout.Post("/api/user/orders", h.Load)
готово

. +

2022-12-04 14:14 UTC, dimsonson commented on internal/services/order.go
> +	linkUpd := fmt.Sprintf("%s/api/orders/%s", svc.CalcSys, orderNum)
готово

. +

2022-12-04 16:15 UTC, dimsonson commented on cmd/gophermart/workerpool/worker.go
> +func (wr *Worker) Job(task models.Task) {
готово

. +

2022-12-04 16:28 UTC, dimsonson commented on cmd/gophermart/workerpool/worker.go
> +			wr.timeoutW = time.NewTicker(time.Duration(timeout) * 1000 * time.Millisecond)
готово

. +

2022-12-05 18:08 UTC, dimsonson commented on cmd/gophermart/main.go
> +	}
готово

. +

2022-12-07 20:19 UTC, lostsequence requested changes

2022-12-07 20:19 UTC, lostsequence commented on cmd/gophermart/workerpool/worker.go
> +		case <-wr.timeoutW.C:
может просто ретрай оставить и не использовать отдельный тикер ?

2022-12-07 20:19 UTC, lostsequence commented on cmd/gophermart/workerpool/pool.go
> +				p.collector <- p.TasksQ.PopFront()
можно, например, просто в канал collector писать при получении заказа ? что дает прослойка в виде Deque ?

2022-12-07 20:19 UTC, lostsequence commented on internal/services/tests/order_test.go
> +	svc := services.NewOrderService(s, "", nil)
почему в тесте сервиса мокаем сам сервис ?

2022-12-07 20:19 UTC, lostsequence commented on internal/services/order.go
> +	rPost, err := http.Post(insertLink, "application/json", strings.NewReader(bodyJSON))
лучше вынести в интерфейс обращение к внешней системе, а то не потестить будет

2022-12-08 09:17 UTC, dimsonson commented on cmd/gophermart/workerpool/pool.go
> +)
готово

. +

2022-12-08 09:20 UTC, dimsonson commented on cmd/gophermart/workerpool/worker.go
> +			<-time.After(time.Duration(timeout) * 1000 * time.Millisecond)
готово

. +

2022-12-08 09:54 UTC, dimsonson commented on cmd/gophermart/workerpool/pool.go
> +				p.collector <- p.TasksQ.PopFront()
дает динамическую очередь, размер которой не зависит от буфера канала
если писать сразу в канал, то при его заполнении будет блокировка

2022-12-08 09:55 UTC, dimsonson commented on internal/services/tests/order_test.go
> +	svc := services.NewOrderService(s, "", nil)
мокаем storage, передаем в экземпляр сервиса и вызываем метод сервиса для тестирования

2022-12-08 10:08 UTC, dimsonson commented on cmd/gophermart/main.go
> +	wg.Add(1)
контекст завершает
<-ctx.Done()
по  os.Interrupt

сделаю явную передачу контекста

2022-12-08 10:09 UTC, dimsonson commented on cmd/gophermart/main.go
> +	wg.Add(1)
готово

. +

2022-12-08 10:22 UTC, dimsonson commented on cmd/gophermart/main.go
> +	stop()
готово

. +

2022-12-08 10:33 UTC, dimsonson commented on cmd/gophermart/workerpool/pool.go
> +	defer p.mu.Unlock()
думаю да, горутина читает или изменяет данные, которые могут использоваться другим потоком

2022-12-08 10:33 UTC, dimsonson commented on cmd/gophermart/workerpool/pool.go
> +	defer p.mu.Unlock()
готово

. +

2022-12-08 10:55 UTC, dimsonson commented on internal/services/tests/order_test.go
> +	svc := services.NewOrderService(s, "", nil)
готово

. +

2022-12-08 11:03 UTC, dimsonson commented on cmd/gophermart/workerpool/pool.go
> +	ctx           context.Context
готово

. +

2022-12-08 17:59 UTC, dimsonson commented on internal/services/order.go
> +	rPost, err := http.Post(insertLink, "application/json", strings.NewReader(bodyJSON))
готово

. +

2022-12-11 18:39 UTC, lostsequence commented on cmd/gophermart/main.go
> +		log.Fatal().Err(err).Msgf("HTTP server ListenAndServe error: %v", err)
не используй log.Fatal, когда есть graceful shutdown.
тут надо еще вызвать отмену контекста, чтобы завершить работу

2022-12-11 18:48 UTC, lostsequence commented on internal/services/tests/order_test.go
> +	svc := services.NewOrderService(s, nil, nil)
тут я не понял как отработает без моков на requestProvider и на pool

2023-01-15 16:00 UTC, dimsonson commented on internal/services/tests/order_test.go
> +	svc := services.NewOrderService(s, nil, nil)
Да)

. Готово

2023-05-29 08:34 UTC, merged